# Generated by Django 6.0.2 on 2026-02-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0003_myappointments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myappointments',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
