# Generated by Django 6.0.2 on 2026-03-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0005_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myappointments',
            old_name='phonenumber',
            new_name='phone',
        ),
    ]
