# Generated by Django 6.0.2 on 2026-03-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0006_rename_phonenumber_myappointments_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myappointments',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
